loans/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('request/', views.RequestLoan.as_view(), name='request_loan'),
]

loans_admin/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans_admin'

urlpatterns = [
    #path('user/create/', views.SignUpView.as_view(), name='user_create'),
    path('', views.Dash.as_view(), name='loans_admin_home'),

    #payments
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('payment/<int:pk>/detail/', views.PaymentsView.as_view(), name='payment_details'),
    path('payments/pending/', views.PendingPayments.as_view(), name='pending_payments'),
    #path('payment/add/<int:loan_pk>/', views.MakePayment.as_view(), name='make_payment'),

    #customers
    path('customers/', views.CustomerView.as_view(), name='customers'),
    path('customer/<int:pk>/loans/', views.CustomerView.as_view(), name='customer_loans'),
    path('customers/update/all/', views.UpdateCustomerView.as_view(), name='update_customers'),

    #loans list
    path('loans/active/list/', views.LoansView.as_view(), name='active_loans'),
    path('loans/pending/list/', views.PendingLoansView.as_view(), name='pending_loans'),
    path('loans/completed/list/', views.CompletedLoans.as_view(), name='completed_loans'),
    #path('loans/pastdue/list/', views.CompletedLoans.as_view(), name='past_due_loans'),
    path('loans/<int:pk>/details', views.LoanDetails.as_view(), name='loan_details'),
    #update loans
    path('loans/<int:pk>/update', views.LoansUpdate.as_view(), name='loan_update'),

    #summary
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('summary/list/', views.SummaryList.as_view(), name='summary_list'),
    path('summary/<int:pk>/detail/', views.SummeryDetail.as_view(), name='summary_details'),
    path('summary/month/list/<int:show_previous_year>/', views.MonthSummeryList.as_view(), name='month_summary_list'),
    path('summary/month/detail/<int:month>/<int:year>/<str:month_name>/', views.MonthSummeryDetail.as_view(),
         name='month_summary_detail'),

    #new loans
    path('loans/add/', views.IssueLoanNewCustomer.as_view(), name='new_loan_new_client'),
    path('loans/add/existing/', views.IssueLoanExistingCustomer.as_view(), name='new_loan_existing_client'),
    path('loans/reject/', views.LoanRejection.as_view(), name='loan_reject'),

    #stations
    path('stations/', views.StationsView.as_view(), name='stations'),

    #opening balance
    path('opening/balance/', views.SaveOpeningBalance.as_view(), name='opening_balance'),

    #savings
    path('savings/', views.SavingsView.as_view(), name='savings'),

    #legal
    path('terms', views.TermsView.as_view(), name='terms')
]

loans_admin/models.py
from django.db import models

from investor.models import StriveUser, Station


# Create your models here.
class CustomerInstitution(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Customer(models.Model):
    SEX = (
        ('1', 'Female'),
        ('2', 'Male'),
    )
    name = models.CharField(max_length=50, help_text='Enter Full Name')
    address = models.CharField(max_length=50, help_text='Enter Address')
    phone = models.CharField(max_length=13)
    email = models.EmailField(blank=True, null=True)
    date_of_birth = models.DateField(help_text='Enter Customer\'s Date Of Birth  (YYYY-MM-DD)', blank=True, null=True)
    nrc = models.CharField(max_length=15, help_text='Enter NRC number', blank=True, null=True)
    sex = models.CharField(max_length=1, choices=SEX, help_text='Set The Customer\'s Gender')
    institution = models.ForeignKey(CustomerInstitution, help_text='Enter Customer\'s Related Institution', blank=True, null=True, on_delete=models.DO_NOTHING)
    #trading_area = models.CharField(max_length=50, help_text='Enter Customer\'s Trading Area')
    station = models.ForeignKey(Station, on_delete=models.CASCADE, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    black_listed = models.BooleanField(default=False)

    def __str__(self):
        if self.nrc:
            return str(self.name) + ' ' + str(self.nrc)
        else:
            return str(self.name)


class Expenses(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    amount = models.FloatField(help_text='Enter Expense Amount')
    user = models.ForeignKey(StriveUser, on_delete=models.DO_NOTHING)
    description = models.CharField(max_length=100, help_text='What was the money used for')
    date = models.DateTimeField(auto_now_add=True)


class Summery(models.Model):
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    total_payments = models.FloatField(blank=True, null=True, default=0)
    balance_brought_forward = models.FloatField(blank=True, null=True)
    total_expenditure = models.FloatField(blank=True, null=True, default=0)
    total_pending_loans = models.FloatField(blank=True, null=True, default=0)
    total_active_loans = models.FloatField(blank=True, null=True, default=0)
    total_expected_cash = models.FloatField(blank=True, null=True, default=0)
    total_cash_at_hand = models.FloatField(blank=True, null=True, default=0)
    total_profits = models.FloatField(blank=True, null=True, default=0)
    date = models.DateField(auto_now_add=True)
    close_time = models.TimeField(auto_now=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date) + '___' + str(self.station)

    class Meta:
        verbose_name_plural = 'Summaries'

loans_admin/forms.py
from django import forms

from investor.models import Station
from loans_admin.models import Customer


class DateInput(forms.DateInput):
    input_type = 'date'

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['black_listed', 'is_active']
        widgets = {'date_of_birth': DateInput()}


StationInventoryFormSet = forms.modelformset_factory(Station, fields=('name', 'address', 'phone', 'available_funds','working_capital'), extra=2)
CustomerFormSet = forms.modelformset_factory(Customer, fields=('name', 'address', 'phone', 'email', 'date_of_birth', 'nrc', 'sex', 'institution', 'is_active', 'black_listed'), extra=5, can_delete=True)

loans_admin/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.views.generic import TemplateView, ListView, FormView, DetailView, UpdateView

import loans.forms
from loans_admin.models import Customer, Expenses, Summery
from loans.models import Loan, LoanPayment
from investor.models import Station, Deposit
from django.db.models import Q
from datetime import datetime, timedelta
from loans_admin import forms
from django.urls import reverse_lazy
from django.contrib import messages
from django.db import transaction
from django.utils import timezone
#from django.contrib.messages.views import SuccessMessageMixin
#email imports
from django.core import mail
from django.template import Context
from django.template.loader import render_to_string, get_template

# Create your views here.



class Dash(TemplateView):
    template_name = 'loans_admin/dash.html'

    def get(self, request, *args, **kwargs):
        #get loans
        loans_total = 0
        loans_and_profit = 0
        pending_loans_total = 0

        #number of stations
        #stations = Station.objects.filter(institution=request.user.station.institution).count()


        loans = Loan.objects.filter(Q(station=request.user.station) & (Q(status='1') | Q(status='2')))

        # active_loans
        active_loans = loans.filter(status='2')

        # pending loans
        pending_loans = loans.filter(status='1')

        for loan in pending_loans:
            pending_loans_total += loan.amount

        for loan in active_loans:
            loans_total += loan.amount
            loans_and_profit += loan.get_total_amount()

        #total recovered money
        loans_total_recovered = 0
        for loan in loans:
            loans_total_recovered += loan.get_total_payments()

        #percent recovered
        try:
            percent_recovered = (loans_total_recovered/loans_and_profit) * 100
        except ZeroDivisionError:
            percent_recovered = 100

        #total interest
        total_interest = loans_and_profit - loans_total
        context = {'loans': loans, 'active_loans': active_loans, 'pending_loans': pending_loans, 'pending_loans_total': pending_loans_total, 'loans_total': loans_total, 'total_interest': total_interest,
                   'loans_and_profit': loans_and_profit,'loans_total_recovered': loans_total_recovered, 'percent_recovered':percent_recovered}
        return render(request, self.template_name, context)

 # payments...


class PaymentsView(ListView):
    template_name = 'loans_admin/payments.html'
    model = LoanPayment
    context_object_name = 'payments'
    paginate_by = '30'

    def get_queryset(self):
        payments = LoanPayment.objects.filter(Q(station=self.request.user.station)).order_by('-id')
        return payments

class PendingPayments(ListView):
    template_name = 'loans_admin/pending_payments.html'
    model = Loan
    context_object_name = 'loans'

    def get_queryset(self):

        loans = Loan.objects.filter(Q(station=self.request.user.station) & Q(status='2'))
        all_payments = LoanPayment.objects.filter(Q(station=self.request.user.station) &
                                                  Q(date__day=datetime.today().day) &
                                                  Q(date__month=datetime.today().month) &
                                                  Q(date__year=datetime.today().year))

        for payment in all_payments:
            loans.exclude(Q(pk=payment.loan.id) & Q(issue_date__year=datetime.today().year) &
                          Q(issue_date__month=datetime.today().month) & Q(issue_date__day=datetime.today().day))
        return loans

    def get_context_data(self, *, object_list=None, **kwargs):
        kwargs['pending'] = True
        return super().get_context_data(**kwargs)

# payments end ....


class CustomerView(ListView):
    template_name = 'loans_admin/customers.html'
    model = Customer
    context_object_name = 'customers'
    paginate_by = '30'

    def get_queryset(self):
        q = Customer.objects.filter(Q(station=self.request.user.station) & Q(is_active=True)).order_by('-id')
        return q

class UpdateCustomerView(FormView):
    template_name = 'loans_admin/update_customers.html'

    def get(self, request, *args, **kwargs):
        customers = Customer.objects.filter(station=request.user.station)

        formset = forms.CustomerFormSet(queryset=customers)

        context = {'formset':formset, 'show_delete': True}
        return  render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        customers = Customer.objects.filter(station=request.user.station)

        formset = forms.CustomerFormSet(request.POST or None, queryset=customers)

        if formset.is_valid():
            with transaction.atomic():
                instances = formset.save(commit=False)
                for obj in formset.deleted_objects:
                    obj.delete()

                for instance in instances:
                    instance.station = request.user.station
                    instance.save()
                messages.success(request, 'Customers Updated Successfully')
        else:
            #print(formset.errors)
            messages.error(request, 'The Form Did Not Validate, Please Check Your Entries')
            messages.error(request, '{}'.format(formset.errors))
            return HttpResponseRedirect(reverse_lazy('loans_admin:update_customers'))
        return HttpResponseRedirect(reverse_lazy('loans_admin:customers'))


class PendingLoansView(FormView):
    template_name = 'loans_admin/pending_loan_list.html'

    def get(self, request, *args, **kwargs):
        loans = Loan.objects.filter(Q(status='1') & Q(station=request.user.station)).order_by('-id')

        context = {'loans': loans, }
        return render(request, self.template_name, context)

    #approve loans
    def post(self, request, *args, **kwargs):
        approved_amount = float(request.POST.get('approved_amount'))
        loan_id = request.POST.get('loan_id')
        try:
            loan = Loan.objects.get(pk=loan_id)
            # set the due date
            due_date = None
            if loan.term == '1':
                due_date = timezone.now() + timedelta(7)
            elif loan.term == '2':
                due_date = timezone.now() + timedelta(14)
            elif loan.term == '3':
                due_date = timezone.now() + timedelta(30)
            elif loan.term == '4':
                due_date = timezone.now() + timedelta(60)
            elif loan.term =='5':
                due_date = timezone.now() + timedelta(90)

            loan.due_date = due_date
            if loan.amount != approved_amount:
                loan.amount = approved_amount

            loan.status = '2'
            loan.issue_date = timezone.now()
            loan.approved_by = request.user

            #change the value for available funds
            loan.station.available_funds -= float(loan.amount)
            loan.station.save()
            #save loan changes
            loan.save()

            #send customer email
            if loan.customer.email:
                context = {'loan': loan}
                message_body = get_template('loans_admin/loan_approval_mail.html').render(context)

                try:
                    emails = []
                    # instantiate email
                    email = mail.EmailMessage(
                        subject='Your Loan({}) Has Been Approved.'.format(loan.get_loan_id()),
                        body= message_body,
                        to=[str(loan.customer.email), ],
                    )
                    email.content_subtype = "html"
                    emails.append(email)
                    # sending Email Using EmailMessage
                    # open a connection
                    connection = mail.get_connection()
                    connection.open()
                    connection.send_messages(emails)
                    connection.close()
                    messages.success(request, 'Customer Email Sent.')
                except:
                    messages.error(request, 'Sorry We Could Not Send The Customer Email')

        except Loan.DoesNotExist:
            messages.error(request, 'I couldn\'t Find The Loan For Some Reason. I must be drunk')
            return HttpResponseRedirect(reverse_lazy('loans_admin:pending_loans'))
        messages.success(request, 'Loan Approved')
        return HttpResponseRedirect(reverse_lazy('loans_admin:active_loans'))


class LoansView(FormView):
    template_name = 'loans_admin/loan_list.html'

    def get(self, request, *args, **kwargs):
        loan_list = Loan.objects.filter(Q(station=request.user.station) & Q(status='2')).order_by('-id')

        context = {'loans': loan_list,}
        return render(request, self.template_name, context)

    #loan repayments
    def post(self, request, *args, **kwargs):
        # date
        date = datetime.today()

        #record payment
        amount = request.POST.get('amount')
        loan_id = request.POST.get('loan_id')
        payment_type = request.POST.get('payment_type')
        confirm_re_pay = request.POST.get('confirm_re_pay')
        #print(confirm_re_pay)
        try:
            loan = Loan.objects.get(pk=loan_id)
            balance = loan.get_balance()

             # check if there is a payment for this loan for today
            existing_payments = LoanPayment.objects.filter(Q(loan=loan) & Q(date__day=date.day)& Q(date__month=date.month) & Q(date__year=date.year))

            if existing_payments.count() > 0:
                # if user knows what they are doing
                if confirm_re_pay:
                    # make the payment
                    payment = LoanPayment.objects.create(loan=loan, received_by=request.user, amount=amount,
                                                         station=request.user.station, payment_type=payment_type)

templates/loans_admin/customers.html
{% extends 'loans_admin/base.html' %}
{% block title %}Customers{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block portfolio_section %}
    {% if customers %}
             {% for customer in customers %}

              <!--Loans payments Modal-->
                 <div class="modal fade" id="loanDetail{{ customer.id }}" tabindex="-1" role="dialog" aria-labelledby="loanDetail{{ customer.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="depositInstructionTitle">{{ customer }} Loans</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalBody">

                        {% if customer.loan_set.all|length > 0 %}
                            {% for loan in customer.loan_set.all reversed %}
                                <p><strong>Loan ID{{ loan.get_loan_id }}</strong><br>Amount:{{ loan.amount }}
                                    <br>Repayment Amount:K {{ loan.get_total_amount }}
                                    <br>Application Date: {{ loan.application_date }}
                                    <br>Issue Date: {{ loan.issue_date }}
                                    <br>Due Date: {{ loan.due_date }}
                                    <br>Interest Rate: {{ loan.get_interest_percentage }}
                                    <br>Status: {{ loan.get_status_display }}
                                </p>
                                <p class="text-success">Loan Payments</p>
                                    {% if loan.loanpayment_set.all|length > 0 %}
                                         <div class="table-responsive">
                                             <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>No.</th>
                                                        <th>Amount</th>
                                                        <th>Date</th>
                                                        <th>Balance</th>
                                                    </tr>
                                                </thead>

                                                <tbody id="inv_tbody">
                                                {% for payment in loan.loanpayment_set.all %}
                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>
                                                        <td>K {{ payment.amount | floatformat:2 }}</td>
                                                        <td>{{ payment.date }}</td>
                                                        <td>K {{ payment.balance | floatformat:2 }}</td>
                                                    </tr>

                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    {% else %}
                                        <div class="row">
                                     <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                                        <div>
                                            <h5 class="text-danger">There Are No Payments For This Loan</h5>
                                        </div>
                                     </div>
                                 </div>
                                    {% endif %}
                                <hr style="color: #00bbff">
                            {% endfor %}
                        {% else %}
                            <div class="row">
                                     <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                                        <div>
                                            <h5 class="text-danger">No Loan Data</h5>
                                        </div>
                                     </div>
                                 </div>
                        {% endif %}

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                         </div>
                    </div>

                </div>
             </div>
             {% endfor %}
    {% endif %}
    <!-- End The Modals-->

    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Customers</h3>
            <small>✻ Customer List✻ <br>{{ request.user.get_full_name }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}
          </div>
        </div>


         {% if customers %}
             {% for customer in customers %}
                 <div class="row">
                  <div class="col-md-12">
                    <div class="card demo icon">
                      <div class="card-header">
                        <h5 class="card-title">{{ customer.name }}</h5>
                        <h6 class="card-category">
                            <strong>
                            NRC: {{ customer.nrc }}<br>
                            D.O.B:  {{ customer.date_of_birth }}<br>
                            Gender: {{ customer.get_sex_display }}<br>
                            Address:  {{ customer.address }}<br>
                                Phone: {{ customer.phone }} <a class="text-dark" href="tel:{{ customer.phone }}"><span>&phone;</span></a><br>
                                {% if customer.email %}
                                Email: {{ customer.email }}<br>
                                {% endif %}
                            Institution: {{ customer.institution }}<br>
                            </strong>

                        </h6>
                      </div>
                    <div class="card-footer">
                        <button data-toggle="modal" data-target="#loanDetail{{ customer.id }}" class="btn btn-info">Loans</button>
                    </div>
                    </div>
                  </div>
                 </div><br>

             {% endfor %}
         {% else %}

            <div class="row" data-aos="fade-up" data-aos-delay="100">
              <div class="col-lg-12 d-flex justify-content-center">
                  <h5 class="text-danger">You Have No Customers Yet.<br> Customers Will Show Up Here As You Add Them.</h5>
              </div>
            </div>

            {% endif %}

      </div>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>
    {% endblock portfolio_section %}

{% block javascript %}
    <script src="{% static 'investor/js/strive.js' %}" type="module"></script>
{% endblock %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}

templates/loans_admin/issue_loan.html
{% extends 'loans_admin/base.html' %}
{% block title %}Issue Loans{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}
{% block auto_complete_tags %}
    <link rel="stylesheet" href="{% static 'jquery-ui-1.13.1/jquery-ui.css' %}">
  <script src="{% static 'jquery-ui-1.13.1/external/jquery/jquery.js' %}"></script>
  <script src="{% static 'jquery-ui-1.13.1/jquery-ui.js' %}"></script>
{% endblock auto_complete_tags %}
{% block js_files %}
     <!-- Vendor JS Files -->


  <script src="{% static 'investor/presento/assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/owl.carousel/owl.carousel.min.js'%}"></script>

  <script src="{% static 'investor/presento/assets/vendor/counterup/counterup.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/venobox/venobox.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/aos/aos.js'%}"></script>
  <script>
      // See https://github.com/facebook/react/issues/20829#issuecomment-802088260
      if (!crossOriginIsolated) SharedArrayBuffer = ArrayBuffer;
    </script>

  <!-- Template Main JS File -->
  <script src="{% static 'investor/presento/assets/js/main.js'%}" type="module"></script>
{% endblock js_files%}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>New Loan</h3>
            <small>✻ Fill In The Forms Below To Issue A New Loan ✻ <br>{{ request.user.get_full_name }} | {{ request.user.station }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

        <form action="" method="post">
            {% csrf_token %}
             <div class="row">

                 {% if customer_form %}
                      <div class="col-md-12">
                        <div class="card demo-icons">
                          <div class="card-header">
                            <h5 class="card-title">Customer</h5>
                              <p class="card-category">Customer Details</p>
                          </div>
                           <div class="card-body">
                               {{ customer_form | crispy}}
                           </div>

                        </div>
                      </div>
                 {% else %}
                     <div class="col-md-12">
                        <div class="card demo-icons">
                          <div class="card-header">
                            <h5 class="card-title">Customer</h5>
                          </div>
                           <div class="card-body">
                               <label for="customer_id">Customer ID*</label>
                               <input type="text" class="form-control" placeholder="Enter Customer ID or Name" required id="customer_id" name="customer_id">
                           </div>
                        </div>
                      </div>
                 {% endif %}

             </div>

            <br>
            <div class="row">
              <div class="col-md-12">
                <div class="card demo-icons">
                  <div class="card-header">
                    <h5 class="card-title">Loans</h5>
                      <p class="card-category">Loans Details</p>
                  </div>
                    <div class="card-body">
                        {{ loan_form | crispy }}
                        <div class="text-center">
                            <input class="btn btn-info" type="submit" value="Issue Loan">
                        </div>

                    </div>
                <div class="card-footer text-center">
                    <p>You Can View The Terms and Conditions <a href="{% url 'loans_admin:terms' %}">here</a>.</p>

                </div>
                </div>
              </div>

            </div>
        </form>
      </div>

        <!-- Scripts for autocomplete-->
    <!-- Customer Autocomplete functionality-->
        <script>
            $(function () {
                //alert('kaya');

            //Customer Auto Complete
            $('body').on('focus', '.product', function (e) {
                           $(this).autocomplete({
                               source: availableCustomers,
                               minLength: 1
                           })
                        });

            //Customer ID autoComplete
            var availableCustomers = [
                    {% for customer in customers %}
                        {label: "{{ customer }}", value: "{{ customer.id }}"},
                    {% endfor %}
                ];

            $('#customer_id').autocomplete({
                source: availableCustomers,
                minLength: 1
            });
            //console.log(availableCustomers);


            });


        </script>


    </section><!-- End Portfolio Section -->
    <section class="services"></section>

    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}