loans/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('request/', views.RequestLoan.as_view(), name='request_loan'),
]

loans_admin/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans_admin'

urlpatterns = [
    #path('user/create/', views.SignUpView.as_view(), name='user_create'),
    path('', views.Dash.as_view(), name='loans_admin_home'),

    #payments
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('payment/<int:pk>/detail/', views.PaymentsView.as_view(), name='payment_details'),
    path('payments/pending/', views.PendingPayments.as_view(), name='pending_payments'),
    #path('payment/add/<int:loan_pk>/', views.MakePayment.as_view(), name='make_payment'),

    #customers
    path('customers/', views.CustomerView.as_view(), name='customers'),
    path('customer/<int:pk>/loans/', views.CustomerView.as_view(), name='customer_loans'),
    path('customers/update/all/', views.UpdateCustomerView.as_view(), name='update_customers'),

    #loans list
    path('loans/active/list/', views.LoansView.as_view(), name='active_loans'),
    path('loans/pending/list/', views.PendingLoansView.as_view(), name='pending_loans'),
    path('loans/completed/list/', views.CompletedLoans.as_view(), name='completed_loans'),
    #path('loans/pastdue/list/', views.CompletedLoans.as_view(), name='past_due_loans'),
    path('loans/<int:pk>/details', views.LoanDetails.as_view(), name='loan_details'),
    #update loans
    path('loans/<int:pk>/update', views.LoansUpdate.as_view(), name='loan_update'),

    #summary
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('summary/list/', views.SummaryList.as_view(), name='summary_list'),
    path('summary/<int:pk>/detail/', views.SummeryDetail.as_view(), name='summary_details'),
    path('summary/month/list/<int:show_previous_year>/', views.MonthSummeryList.as_view(), name='month_summary_list'),
    path('summary/month/detail/<int:month>/<int:year>/<str:month_name>/', views.MonthSummeryDetail.as_view(),
         name='month_summary_detail'),

    #new loans
    path('loans/add/', views.IssueLoanNewCustomer.as_view(), name='new_loan_new_client'),
    path('loans/add/existing/', views.IssueLoanExistingCustomer.as_view(), name='new_loan_existing_client'),
    path('loans/reject/', views.LoanRejection.as_view(), name='loan_reject'),

    #stations
    path('stations/', views.StationsView.as_view(), name='stations'),

    #opening balance
    path('opening/balance/', views.SaveOpeningBalance.as_view(), name='opening_balance'),

    #savings
    path('savings/', views.SavingsView.as_view(), name='savings'),

    #legal
    path('terms', views.TermsView.as_view(), name='terms')
]

loans/models.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from investor.models import StriveUser, Station
# Create your models here.
from loans_admin.models import Customer
from django.urls import reverse


class LoanAccount(models.Model):
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    outstanding_balance = models.FloatField() #principle - payment
    date = models.DateTimeField(auto_created=True)
    principle_amount = models.FloatField()
    apr = models.FloatField()

    def get_interest_amount(self):
        if self.outstanding_balance > 0:
            amount = self.outstanding_balance * self.apr
        else:
            amount = self.principle_amount * self.apr
        return amount

    def get_loan_total(self):
        if self.outstanding_balance > 0:
            total = self.outstanding_balance + self.get_interest_amount()
        else:
            total = self.principle_amount + self.get_interest_amount()
        return total

class LoanPayments(models.Model):
    loan = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    amount = models.FloatField()
    date = models.DateTimeField(auto_created=True)

class LoanApplications(models.Model):
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    amount = models.FloatField()
    apr = models.FloatField() # add choices to the form


class Loan(models.Model):
    LOAN_STATUS = (
        ('1', 'Pending'),
        ('2', 'Approved'),
        ('3', 'Completed'),
        ('4', 'Rejected'),
    )
    LOAN_TERM = (
        ('1', 'One Week'),
        ('2', 'Two Weeks'),
        ('3', 'One Month'),
        ('4', 'Two Months'),
        ('5', 'Three Months'),
    )
    PAYMENTS = (
        ('1', 'Weekly'),
        ('2', 'Monthly'),
    )
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE, related_name='customer_user', null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    approved_by = models.ForeignKey(StriveUser, on_delete=models.CASCADE, null=True, blank=True)
    issue_date = models.DateTimeField(default=timezone.now)
    application_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=timezone.now)
    amount = models.FloatField(help_text='Enter loan amount')
    interest_rate = models.FloatField(default=0.37, help_text='Enter Interest Rate As A Decimal Fraction')
    status = models.CharField(choices=LOAN_STATUS, max_length=1, default='1')
    term = models.CharField(max_length=1, choices=LOAN_TERM, default='1', help_text='Whats the term of the loan')
    payment_frequency = models.CharField(max_length=1, default='1', choices=PAYMENTS, help_text='How often will the Customer make Loan Payments')
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    disbursed = models.BooleanField(default=False)

    def get_total_payments(self):
        total = 0
        payments = LoanPayment.objects.filter(Q(station=self.station) &
                                              Q(loan=self.id))
        for payment in payments:
            total +=payment.amount
        return total

    def get_total_amount(self):
        # loan amount plus interest
        interest_amount = self.amount * self.interest_rate
        total = self.amount + interest_amount
        return total

    def get_interest_amount(self):
        # loan interest
        interest_amount = self.amount * self.interest_rate
        return interest_amount

    def get_balance(self):
        # calculate payments made subtract get_total_amount
        balance = self.get_total_amount() - self.get_total_payments()
        return balance

    def get_interest_percentage(self):
        percentage = str(round(self.interest_rate * 100, 2))+ ' %'
        return percentage

    def get_loan_id(self):
        # todo refine this function so as to get a consistent number of digits in the loan ID
        loan_pk = str(self.id)
        id_length = len(loan_pk)
        if self.user:
            user_id = self.user.id
        elif self.customer:
            user_id = self.customer.id
        else:
            user_id = '0'
        # find the number of Zeros to add
        difference = 7 - id_length
        zeros = '0'
        zeros = zeros * difference
        # digits to use for the barcode
        load_id = '{}{}{}'.format(user_id, zeros, loan_pk)
        return load_id

    def __str__(self):
        user = None
        if self.user:
            user = self.user
        else:
            user = self.customer
        return str(self.get_loan_id()) + ': ' + str(user)

    def is_past_due(self):
        if timezone.now() > self.due_date:
            return True

    def get_absolute_url(self):
        return reverse('loans_admin:loan_details', kwargs={'pk': self.pk})


class LoanPayment(models.Model):
    PAYMENT_TYPE = (
        ('CASH', '1'),
        ('MOBILE MONEY', '2'),
    )
    loan = models.ForeignKey(Loan, on_delete=models.DO_NOTHING)
    received_by = models.ForeignKey(StriveUser, on_delete=models.DO_NOTHING)
    date = models.DateTimeField(auto_now_add=True)
    payment_type = models.CharField(max_length=1, choices=PAYMENT_TYPE, default='2')
    amount = models.FloatField()
    balance = models.FloatField(null=True, blank=True)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)

    def get_profits(self):
        profit = self.amount * self.loan.interest_rate
        return profit

    def __str__(self):
        return str(self.loan) + ' ' + str(self.amount)

    #def save(self, *args, **kwargs):
    #    print('saved')
    #    super().save(*args, **kwargs)

loans/forms.py
from django import forms
from loans_admin.models import Customer
from loans.models import Loan, LoanPayment
from investor.models import Station

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ('amount', 'term', "payment_frequency",)


class LoanPaymentForm(forms.ModelForm):
    class Meta:
        model = LoanPayment
        fields = ('amount',)

loans/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import TemplateView, FormView
from Strive.decorators import user_is_investor
from django.utils.decorators import method_decorator
from . import forms
from .models import Loan
from django.db.models import Q

@method_decorator(user_is_investor, name='get')
class Home(TemplateView):
    template_name = 'loans/loan_home.html'

    def get(self, request, *args, **kwargs):
        loans = Loan.objects.filter(Q(user=request.user) & Q(status='1') | Q(status='2'))
        context = {'loans': loans,}
        return render(request, self.template_name, context)


class RequestLoan(FormView):
    template_name = 'loans/issue_loan.html'

    def get(self, request, *args, **kwargs):
        # new loan form
        loan_form = forms.LoanForm()

        #get existing customers
        #customers = Customer.objects.filter(station=request.user.station)

        context = {'loan_form': loan_form,}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        #save new customer
        #customer_id = request.POST.get('customer_id')
        #try:
        #    customer = Customer.objects.get(pk=customer_id)
        #except Customer.DoesNotExist:
        #    messages.error(request, 'Weirdly We Couldn\'t Find The Customer, Please Try Again')
        #    return HttpResponseRedirect(reverse_lazy('loans_admin:new_loan_existing'))

        #save new customer loan
        loan_form = forms.LoanForm(request.POST or None)
        if loan_form.is_valid():
            user = self.request.user
            loan = loan_form.save(commit=False)
            loan.user = user
            #loan.station = request.user.station
            loan.save()
        else:
            messages.error(request, 'The Loan Form Did Not Validate')
            return HttpResponseRedirect(reverse_lazy('loans_admin:new_loan_existing'))
        messages.success(request, 'Loan Application Recorded')
        return HttpResponseRedirect(reverse_lazy('loans:home'))

templates/loans/issue_loan.html
{% extends 'presento/base.html' %}
{% block title %}Issue Loans{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}
{% block auto_complete_tags %}
    <link rel="stylesheet" href="{% static 'jquery-ui-1.13.1/jquery-ui.css' %}">
  <script src="{% static 'jquery-ui-1.13.1/external/jquery/jquery.js' %}"></script>
  <script src="{% static 'jquery-ui-1.13.1/jquery-ui.js' %}"></script>
{% endblock auto_complete_tags %}
{% block js_files %}
     <!-- Vendor JS Files -->


  <script src="{% static 'investor/presento/assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/owl.carousel/owl.carousel.min.js'%}"></script>

  <script src="{% static 'investor/presento/assets/vendor/counterup/counterup.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/venobox/venobox.min.js'%}"></script>
  <script src="{% static 'investor/presento/assets/vendor/aos/aos.js'%}"></script>
  <script>
      // See https://github.com/facebook/react/issues/20829#issuecomment-802088260
      if (!crossOriginIsolated) SharedArrayBuffer = ArrayBuffer;
    </script>

  <!-- Template Main JS File -->
  <script src="{% static 'investor/presento/assets/js/main.js'%}" type="module"></script>
{% endblock js_files%}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>New Loan</h3>
            <small>✻ Fill In The Forms Below To Issue A New Loan ✻ <br>{{ request.user.get_full_name }} | {{ request.user.station }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="card demo-icons">
                  <div class="card-header">
                    <h5 class="card-title">Loan Request</h5>
                      <p class="card-category">Loan Details</p>
                  </div>
                    <div class="card-body">
                        {{ loan_form | crispy }}
                        <div class="text-center">
                            <input class="btn btn-info" type="submit" value="Request Loan">
                        </div>

                    </div>
                <div class="card-footer text-center">
                    <p>You Can View The Loan Terms and Conditions <a href="{% url 'loans_admin:terms' %}">here</a>.</p>

                </div>
                </div>
              </div>

            </div>
        </form>
      </div>

        <!-- Scripts for autocomplete-->
    <!-- Customer Autocomplete functionality-->
        <script>
            $(function () {
                //alert('kaya');

            //Customer Auto Complete
            $('body').on('focus', '.product', function (e) {
                           $(this).autocomplete({
                               source: availableCustomers,
                               minLength: 1
                           })
                        });

            //Customer ID autoComplete
            var availableCustomers = [
                    {% for customer in customers %}
                        {label: "{{ customer }}", value: "{{ customer.id }}"},
                    {% endfor %}
                ];

            $('#customer_id').autocomplete({
                source: availableCustomers,
                minLength: 1
            });
            //console.log(availableCustomers);


            });


        </script>


    </section><!-- End Portfolio Section -->
    <section class="services"></section>

    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}

templates/loans/loan_home.html
{% extends 'presento/base.html' %}
{% block title %}Savings{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Loans</h3>
            <small>✻ A Breakdown Of Your Outstanding loans ✻ <br>{{ request.user.get_full_name }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

         <div class="row">
         {% if loans %}
             {% for loan in loans %}
                 <!--Page renderings -->

                  <div class="col-md-12">
                    <div class="card demo icon">
                      <div class="card-header">
                        <h5 class="card-title">{{ customer.name }}</h5>
                        <h6 class="card-category">
                            <strong>
                                <h4>Loan: {{ loan }}</h4>
                                Amount:  ZMW {{ loan.amount }}<br>
                                Interest: ZMW {{ loan.get_interest_amount }}<br>
                                Repayment Total: ZMW {{ loan.get_total_amount }}<br>
                                Application Date: {{ loan.application_date }}<br>
                                Rate: {{ loan.get_interest_percentage }}<br>

                                Term: {{ loan.get_term_display }}<br>
                                Status: {{ loan.get_status_display }}<br>
                                {% if loan.status == '2' %}
                                    {% if loan.disbursed %}
                                        Disbursement: Funds disbursed
                                    {% else %}
                                        Disbursement: Pending
                                    {% endif %}
                                {% endif %}
                            </strong>

                        </h6>
                      </div>
                    <div class="card-footer">
                    {% if loan.status == '2' and loan.disbursed %}
                        <button  class="btn btn-primary" data-toggle="modal" data-target="#loanApprovalModel{{ loan.id }}">Make Payment</button><!--MODEL-->
                        {% elif loan.status == '1' %}
                        <button data-toggle="modal" data-target="#loanRejectionModel{{ loan.id }}" class="btn btn-danger">Cancel Loan</button><!--modal-->
                        {% endif %}
                    </div>
                    </div>
                  </div>
                 <br>
             {% endfor %}
         {% else %}
             <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                <div>
                    <h5 class="text-info">Your Have No Outstanding Loans.<br> Use The Request Button Below to Request a loan.</h5>
                </div>
             </div>
             </div>

             <br>
         <div class="row">
             <div class="col-md-12 col-lg-12 col-sm-12 text-center">
             <a class="btn btn-info" href="{% url 'loans:request_loan' %}">Request Loan</a><br>
             <small>Our Loans are subject to the terms and conditions described <a href="">here</a>. </small>
             </div>

            {% endif %}


        </div>
      </div>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>
    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}