loans/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('request/', views.RequestLoan.as_view(), name='request_loan'),
]

loans_admin/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans_admin'

urlpatterns = [
    #path('user/create/', views.SignUpView.as_view(), name='user_create'),
    path('', views.Dash.as_view(), name='loans_admin_home'),

    #payments
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('payment/<int:pk>/detail/', views.PaymentsView.as_view(), name='payment_details'),
    path('payments/pending/', views.PendingPayments.as_view(), name='pending_payments'),
    #path('payment/add/<int:loan_pk>/', views.MakePayment.as_view(), name='make_payment'),

    #customers
    path('customers/', views.CustomerView.as_view(), name='customers'),
    path('customer/<int:pk>/loans/', views.CustomerView.as_view(), name='customer_loans'),
    path('customers/update/all/', views.UpdateCustomerView.as_view(), name='update_customers'),

    #loans list
    path('loans/active/list/', views.LoansView.as_view(), name='active_loans'),
    path('loans/pending/list/', views.PendingLoansView.as_view(), name='pending_loans'),
    path('loans/completed/list/', views.CompletedLoans.as_view(), name='completed_loans'),
    #path('loans/pastdue/list/', views.CompletedLoans.as_view(), name='past_due_loans'),
    path('loans/<int:pk>/details', views.LoanDetails.as_view(), name='loan_details'),
    #update loans
    path('loans/<int:pk>/update', views.LoansUpdate.as_view(), name='loan_update'),

    #summary
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('summary/list/', views.SummaryList.as_view(), name='summary_list'),
    path('summary/<int:pk>/detail/', views.SummeryDetail.as_view(), name='summary_details'),
    path('summary/month/list/<int:show_previous_year>/', views.MonthSummeryList.as_view(), name='month_summary_list'),
    path('summary/month/detail/<int:month>/<int:year>/<str:month_name>/', views.MonthSummeryDetail.as_view(),
         name='month_summary_detail'),

    #new loans
    path('loans/add/', views.IssueLoanNewCustomer.as_view(), name='new_loan_new_client'),
    path('loans/add/existing/', views.IssueLoanExistingCustomer.as_view(), name='new_loan_existing_client'),
    path('loans/reject/', views.LoanRejection.as_view(), name='loan_reject'),

    #stations
    path('stations/', views.StationsView.as_view(), name='stations'),

    #opening balance
    path('opening/balance/', views.SaveOpeningBalance.as_view(), name='opening_balance'),

    #savings
    path('savings/', views.SavingsView.as_view(), name='savings'),

    #legal
    path('terms', views.TermsView.as_view(), name='terms')
]

loans/models.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from investor.models import StriveUser, Station
# Create your models here.
from loans_admin.models import Customer
from django.urls import reverse


class LoanAccount(models.Model):
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    outstanding_balance = models.FloatField() #principle - payment
    date = models.DateTimeField(auto_created=True)
    principle_amount = models.FloatField()
    apr = models.FloatField()

    def get_interest_amount(self):
        if self.outstanding_balance > 0:
            amount = self.outstanding_balance * self.apr
        else:
            amount = self.principle_amount * self.apr
        return amount

    def get_loan_total(self):
        if self.outstanding_balance > 0:
            total = self.outstanding_balance + self.get_interest_amount()
        else:
            total = self.principle_amount + self.get_interest_amount()
        return total

class LoanPayments(models.Model):
    loan = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    amount = models.FloatField()
    date = models.DateTimeField(auto_created=True)

class LoanApplications(models.Model):
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    amount = models.FloatField()
    apr = models.FloatField() # add choices to the form


class Loan(models.Model):
    LOAN_STATUS = (
        ('1', 'Pending'),
        ('2', 'Approved'),
        ('3', 'Completed'),
        ('4', 'Rejected'),
    )
    LOAN_TERM = (
        ('1', 'One Week'),
        ('2', 'Two Weeks'),
        ('3', 'One Month'),
        ('4', 'Two Months'),
        ('5', 'Three Months'),
    )
    PAYMENTS = (
        ('1', 'Weekly'),
        ('2', 'Monthly'),
    )
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE, related_name='customer_user', null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    approved_by = models.ForeignKey(StriveUser, on_delete=models.CASCADE, null=True, blank=True)
    issue_date = models.DateTimeField(default=timezone.now)
    application_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=timezone.now)
    amount = models.FloatField(help_text='Enter loan amount')
    interest_rate = models.FloatField(default=0.37, help_text='Enter Interest Rate As A Decimal Fraction')
    status = models.CharField(choices=LOAN_STATUS, max_length=1, default='1')
    term = models.CharField(max_length=1, choices=LOAN_TERM, default='1', help_text='Whats the term of the loan')
    payment_frequency = models.CharField(max_length=1, default='1', choices=PAYMENTS, help_text='How often will the Customer make Loan Payments')
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    disbursed = models.BooleanField(default=False)

    def get_total_payments(self):
        total = 0
        payments = LoanPayment.objects.filter(Q(station=self.station) &
                                              Q(loan=self.id))
        for payment in payments:
            total +=payment.amount
        return total

    def get_total_amount(self):
        # loan amount plus interest
        interest_amount = self.amount * self.interest_rate
        total = self.amount + interest_amount
        return total

    def get_interest_amount(self):
        # loan interest
        interest_amount = self.amount * self.interest_rate
        return interest_amount

    def get_balance(self):
        # calculate payments made subtract get_total_amount
        balance = self.get_total_amount() - self.get_total_payments()
        return balance

    def get_interest_percentage(self):
        percentage = str(round(self.interest_rate * 100, 2))+ ' %'
        return percentage

    def get_loan_id(self):
        # todo refine this function so as to get a consistent number of digits in the loan ID
        loan_pk = str(self.id)
        id_length = len(loan_pk)
        if self.user:
            user_id = self.user.id
        elif self.customer:
            user_id = self.customer.id
        else:
            user_id = '0'
        # find the number of Zeros to add
        difference = 7 - id_length
        zeros = '0'
        zeros = zeros * difference
        # digits to use for the barcode
        load_id = '{}{}{}'.format(user_id, zeros, loan_pk)
        return load_id

    def __str__(self):
        user = None
        if self.user:
            user = self.user
        else:
            user = self.customer
        return str(self.get_loan_id()) + ': ' + str(user)

    def is_past_due(self):
        if timezone.now() > self.due_date:
            return True

    def get_absolute_url(self):
        return reverse('loans_admin:loan_details', kwargs={'pk': self.pk})


class LoanPayment(models.Model):
    PAYMENT_TYPE = (
        ('CASH', '1'),
        ('MOBILE MONEY', '2'),
    )
    loan = models.ForeignKey(Loan, on_delete=models.DO_NOTHING)
    received_by = models.ForeignKey(StriveUser, on_delete=models.DO_NOTHING)
    date = models.DateTimeField(auto_now_add=True)
    payment_type = models.CharField(max_length=1, choices=PAYMENT_TYPE, default='2')
    amount = models.FloatField()
    balance = models.FloatField(null=True, blank=True)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)

    def get_profits(self):
        profit = self.amount * self.loan.interest_rate
        return profit

    def __str__(self):
        return str(self.loan) + ' ' + str(self.amount)

    #def save(self, *args, **kwargs):
    #    print('saved')
    #    super().save(*args, **kwargs)

templates/tamara/car_details.html
{% extends 'tamara/base.html' %}
{% block title %}Car Details{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block who_we_are %}
    Account RoundUp
    actual balance
    available balance
{% endblock %}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Loan Details</h3>
            <small>{{ request.user.get_full_name }} | {{ request.user.station }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

         <div class="row">

          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">{{ loan.customer }} </h5>
                  <p class="card-category"><strong>Loan ID{{ loan.get_loan_id }}</strong><br>Amount:{{ loan.amount }}
                                    <br>Repayment Amount:K {{ loan.get_total_amount }}
                                    <br>Issue Date: {{ loan.issue_date }}
                                    <br>Interest Rate: {{ loan.get_interest_percentage }}
                                    <br>Status: {{ loan.get_status_display }}
                                </p>
              </div>
               <div class="card-body">
                   <p>Loan Payments</p>
                    <div class="table-responsive">
				        <table class="table table-striped">
                    <thead>
						<tr>
							<th>No.</th>
							<th>Amount</th>
							<th>Date</th>
							<th>Balance</th>
						</tr>
					</thead>

					<tbody id="inv_tbody">
                    {% for payment in loan.loanpayment_set.all %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
							<td>{{ payment.amount | floatformat:2 }}</td>
							<td>{{ payment.date }}</td>
                            <td>{{ payment.balance | floatformat:2 }}</td>
						</tr>

                    {% endfor %}
					</tbody>
				</table>
			</div>
               </div>


            </div>
          </div>

         </div>
      </div>
          <hr>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>

    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}




<div class="modal-body" id="modalBody">
                <p>{{ loan.customer }}<br>{{ loan.customer.phone }}<br>{{ loan.customer.address }}</p>


                </div>

templates/tamara/car_list.html
{% extends 'tamara/base.html' %}
{% block title %}Cars{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block portfolio_section %}


    {% if cars %}
        {% for car in cars %}
            <!-- Modals for loans -->
                 <!--Loan approval Modal-->
                 <div class="modal fade" id="loanPaymentModel{{ loan.id }}" tabindex="-1" role="dialog" aria-labelledby="loanPaymentModel{{ loan.id }}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="loanPaymentModelTitle">Loan {{ loan.get_loan_id }} Payment</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form method="post" action="" id="{{ loan.id }}">
                                {% csrf_token %}
                            <div class="modal-body" id="modalBody">
                                    <label for="{{ loan.id }}">Enter Payment Amount:<span class="asteriskField">*</span></label>
                                    <input placeholder="Enter Amount" required class="form-control" id="{{ loan.id }}" name="amount" step="any" type="number" max="{{ loan.get_balance }}">
                                <br>
                                    <div id="div_id_payment_type" class="form-group">
                                        <label for="id_payment_type" class="requiredField">
                                            Paid By:<span class="asteriskField">*</span>
                                        </label>
                                        <div class="">
                                        <select name="payment_type" class="select form-control" id="id_payment_type">
                                            <option value="1" selected="">Cash</option> <option value="2">Mobile Money</option>
                                        </select>
                                        <small id="hint_id_payment_type" class="form-text text-muted">What Mode Of Payment Was Used</small>
                                    </div>
                                    </div>
                                    <input type="hidden" name="loan_id" value="{{ loan.id }}">


                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary" id="confirmLoan">Make Payment</button>
                             </div>
                            </form>
                        </div>
                 </div>
             </div>

            <!--Loan Detail Modal-->
            <div class="modal fade" id="loanDetail{{ loan.id }}" tabindex="-1" role="dialog" aria-labelledby="loanDetail{{ loan.id }}" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="depositInstructionTitle">Loan Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalBody">
                <p>{{ loan.customer }}<br>{{ loan.customer.phone }} <a class="text-dark" href="tel:{{ loan.customer.phone }}"><span>&phone;</span></a><br>{{ loan.customer.address }}</p>
                <p>Loan Payments</p>
                {% if loan.loanpayment_set.all|length > 0 %}
                     <div class="table-responsive">
                         <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                    <th>Balance</th>
                                </tr>
                            </thead>

                            <tbody id="inv_tbody">
                            {% for payment in loan.loanpayment_set.all %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ payment.amount | floatformat:2 }}</td>
                                    <td>{{ payment.date }}</td>
                                    <td>{{ payment.balance | floatformat:2 }}</td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="row">
                 <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                    <div>
                        <h5 class="text-danger">There Are No Payments For This Loan</h5>
                    </div>
                 </div>
             </div>
                {% endif %}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Okay</button>
                 </div>
            </div>

        </div>
     </div>
        {% endfor %}
    {% endif %}
    <!-- End The Modals-->

    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Cars Available</h3>
            <small>✻ List Of Cars From Our Trusted Suppliers✻ <br>{{ request.user.get_full_name }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}
          </div>
        </div>


         {% if cars %}
             {% for car in cars %}
                 <div class="row" id="{{ car.id }}">
                  <div class="col-md-12">
                    <div class="card demo icon">
                      <div class="card-header">
                        <h5 class="card-title">{{ loan.customer }}</h5>
                        <h6 class="card-category">
                            <strong>
                                Loan ID: {{ loan.get_loan_id }}<br>
                            Loan Amount:  {{ loan.amount | floatformat:2 }}<br>
                            Amount To Pay: K {{ loan.get_total_amount | floatformat:2 }}<br>
                                Amount Paid: K {{ loan.get_total_payments  | floatformat:2 }}<br>
                                Balance: K {{ loan.get_balance | floatformat:2 }}<br>
                            Issue Date: {{ loan.issue_date }}<br>
                            Rate: {{ loan.get_interest_percentage }}<br>
                            Term: {{ loan.get_term_display }}<br>
                            Payments: {{ loan.get_payment_frequency_display }}
                            </strong>

                        </h6>
                      </div>
                    <div class="card-footer">
                        <button data-toggle="modal" data-target="#loanPaymentModel{{ loan.id }}" class="btn btn-primary">Make Payment</button><!--MODEL-->
                        <button data-toggle="modal" data-target="#loanDetail{{ loan.id }}" class="btn btn-info">Details</button><!--modal-->
                        <a href="{% url 'loans_admin:loans_admin_home' %}" class="btn btn-warning">Update</a>
                    </div>
                    </div>
                  </div>
                 </div><br>
             {% endfor %}
         {% else %}
             <div class="row" data-aos="fade-up" data-aos-delay="100">
                  <div class="col-lg-12 d-flex justify-content-center">
                      <h5 class="text-danger">We Have No Cars To Show You Yet</h5>
                  </div>
                </div>

            {% endif %}


        </div>


    </section><!-- End Portfolio Section -->
    <section class="services"></section>
    {% endblock portfolio_section %}

{% block javascript %}
    <script src="{% static 'investor/js/strive.js' %}" type="module"></script>
{% endblock %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}

templates/tamara/dash.html
{% extends 'tamara/base.html' %}
{% block title %}MoneyGrow with Tamara{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block who_we_are %}
    Account RoundUp
    actual balance
    available balance
{% endblock %}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Dashboard</h3>
            <small>✻ Overview of Your MoneyGrow Account Status ✻ <br>{{ request.user.get_full_name | capfirst }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

         <div class="row">

          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">General Summary </h5>
                  <p class="card-category">General Summary for {{ request.user.get_full_name | capfirst }}</p>
              </div>
               <div class="card-body">
                   <div class="table-responsive">
				<table class="table table-striped">

					<tbody id="inv_tbody">
                        <tr>
                            <td>Amount Lent Out: <strong>K {{ loans_total }}</strong></td>

						</tr>

                        <tr>
                        <td>Expected Interest: <strong>K {{ total_interest }}</strong></td>

                    </tr>

                   <!-- <tr>
                        <td>Amount Available: <strong>K { available_cap }}</strong></td>
                    </tr>-->

                    <tr>
                        <td>No. Active Loans: <strong>{{ active_loans|length }}</strong></td>
                    </tr>

                    <tr>
                        <td>No. Pending Loans: <strong>{{ pending_loans|length }} (K {{ pending_loans_total }})</strong></td>
                    </tr>
                    <tr>
                        <td>Number Of Stations: <strong>{{ stations }}</strong></td>
                    </tr>
					</tbody>
				</table>
			</div>
               </div>

                <p class="card-footer">
                   <strong>Grand Total K {{ loans_and_profit }}</strong> <br>
                </p>
            </div>
          </div>

         </div>

        <br>
        <div class="row">
          <div class="col-md-12">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">Active Loans</h5>
                  <p class="card-category">list of Active Loans</p>
              </div>
                <div class="card-body">
                {% if loans %}
                    <div class="table-responsive">
				<table class="table table-striped">
                    <thead>
						<tr>
							<th>No.</th>
							<th>Amount</th>
							<th>Customer</th>
                            <th>Amount Paid</th>
							<th>Balance</th>
						</tr>
					</thead>

					<tbody id="inv_tbody">
                    {% for loan in loans %}
                        <tr
                                {% if loan.status == '1' %}
                                    class="text-danger"
                                {% endif %}
                        >
                            <td>{{ forloop.counter }}</td>
							<td>{{ loan.amount }}</td>
							<td>{{ loan.customer }}</td>
							<td>{{ loan.get_total_payments}}</td>
                            <td>{{ loan.get_balance }}</td>
						</tr>

                    {% endfor %}
					</tbody>
				</table>
			</div>
                {% else %}
                    <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                <div>
                    <h5 class="text-info">You Have No Active Loans Yet...</h5>
                </div>
             </div>
                {% endif %}
                </div>
            <div class="card-footer">
                <a href="{% url 'loans_admin:active_loans' %}" class="btn btn-success">Goto Full Loans List</a>
            </div>
            </div>
          </div>

        </div>
      </div>
          <hr>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>

    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}

templates/tamara/landing.html
{% extends 'tamara/base.html' %}