investor/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'investor'

urlpatterns = [
    path('user/create/', views.SignUpView.as_view(), name='user_create'),
    path('user/login/', views.Login.as_view(), name='user_login'),
    path('', views.Home.as_view(), name='home'),
    path('savings/', views.SavingsView.as_view(), name='savings'),
    path('savings/withdraw/', views.SavingsWithdraw.as_view(), name='savings_withdraw'),
]

loans/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'loans'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('request/', views.RequestLoan.as_view(), name='request_loan'),
]

investor/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.
class Institution(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Station(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    available_funds = models.FloatField(default=0)
    working_capital = models.FloatField(default=0)


    def __str__(self):
        return str(self.name) + ' ' + str(self.address)

class StriveUser(AbstractUser):
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=13, help_text='Enter Your Phone Number')
    birth_date = models.DateField(auto_created=True, null=True)
    nrc = models.CharField(max_length=15)
    loans_admin = models.BooleanField(default=False)
    station = models.ForeignKey(Station, on_delete=models.CASCADE, null=True, blank=True)
    paying_account = models.CharField(max_length=20, null=True, blank=True)

    def get_full_name(self):
        """
        Return the first_name and middle name plus the last_name, with a space in between.
        """
        if self.middle_name:
            full_name = '%s %s %s' % (self.first_name, self.middle_name, self.last_name)
        else:
            full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name

    def __str__(self):
        return self.get_full_name()

class Account(models.Model):
    ACCOUNT_TYPES = (('Savings', '1'),
                     ('Asset', '2'),)
    account_type = models.CharField(max_length=1, choices=ACCOUNT_TYPES, default='1')
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)

    def get_savings_total(self):
        # get all deposits
        deposits = Deposit.objects.filter(models.Q(account=self.id) & models.Q(spent=False))

        # get cumulative balance
        cumulative_balance = 0
        for deposit in deposits:
            cumulative_balance += deposit.amount

        # get interest earned
        interest = 0
        for deposit in deposits:
            interest += deposit.interest_earned

        # get total balance
        # todo all unspent deposits + interest earned
        total_balance = cumulative_balance + interest

        return [cumulative_balance, total_balance]

class Deposit(models.Model):
    STATUS = (
        ('1','Pending Approval' ),
        ('2', 'Approved' ),
        ('3', 'Active'),
        ('4', 'Withdrawn'),
    )
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    amount = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS, default='1')
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    spent = models.BooleanField(default=False)
    interest_earned = models.FloatField(default=0)
    transaction_id = models.CharField(max_length=50, blank=True, null=True)
    approved_by = models.ForeignKey(StriveUser, on_delete=models.CASCADE, related_name='approved_by', null=True, blank=True)
    date_confirmed = models.DateTimeField(default=timezone.now)

class Withdraw(models.Model):
    STATUS = (
        ('1', 'Pending Approval'),
        ('2', 'Approved'),
        ('3', 'Disbursed'),
    )
    user = models.ForeignKey(StriveUser, on_delete=models.CASCADE)
    amount = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS, default='1')

class Interest(models.Model):
    rate = models.FloatField(blank=True, null=True)
    deposit = models.ForeignKey(Deposit, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

investor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from investor.models import StriveUser

class DateInput(forms.DateInput):
    input_type = 'date'


class SignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = StriveUser
        fields = (
        'first_name', 'middle_name', 'last_name', 'email', 'phone', 'address', 'birth_date',
        'nrc', 'password1', 'password2',)
        widgets = {'birth_date': DateInput()}

investor/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic import TemplateView, FormView, CreateView
from django.conf import settings
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.db.models import Q
from . import forms
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .models import Account, Deposit, Withdraw
from loans.models import LoanAccount
from Strive.decorators import user_is_investor
from django.utils.decorators import method_decorator

# Create your views here.
class Landing(TemplateView):
    template_name = 'investor/landing.html'

class ComingSoon(TemplateView):
    template_name = 'investor/coming_soon.html'

class Login(FormView):
    template_name = 'registration/login.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if user.loans_admin:
                return HttpResponseRedirect(reverse_lazy('loans_admin:loans_admin_home'))
            else:
                return HttpResponseRedirect(reverse_lazy('investor:home'))
        else:
            messages.error(request, 'Your Account Was Not Found. Check Your Username and Password. '
                    'Contact Your Admin If The Problem Persists.')
            return render(request, self.template_name)

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return render(request, self.template_name)
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('investor:home'))


class SignUpView(CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = forms.SignUpForm
    template_name = 'registration/signup_form.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.nrc
        user.save()
        login(self.request, user)
        return redirect('investor:home')

    def form_invalid(self, form):
        messages.error(self.request, 'The Form Did Not Validate')
        return redirect('investor:user_create')


@method_decorator(user_is_investor, name='get')
class Home(TemplateView):
    template_name = 'investor/dash.html'

    def get(self, request, *args, **kwargs):
        assets = 0
        #get loans
        try:
            loans = LoanAccount.objects.get(user=request.user).get_loan_total()
        except LoanAccount.DoesNotExist:
            loans = 0

        # get user savings
        try:
            savings = Account.objects.get(user=request.user, account_type='1').get_savings_total()[1]
        except Account.DoesNotExist:
            savings = 0
        context = {'assets': assets, 'loans': loans, 'savings': savings}
        return render(request, self.template_name, context)


@method_decorator(user_is_investor, name='get')
class SavingsView(FormView):
    template_name = 'investor/savings.html'

    def get(self, request, *args, **kwargs):
        total_interest = 0
        available_balance = 0
        # get user savings
        try:
            savings = Account.objects.get(Q(user=request.user) & Q(account_type='1'))
        except Account.DoesNotExist:
            savings = None

        # get available-balance
        #todo available_balance = mature savings + interest earned on mature savings
        # interest + mature savings
        # get all spent but not withdrawn deposits
        available_deposit = Deposit.objects.filter(Q(user=request.user) & Q(spent=True) & Q(status__in=['1','2','3']))
        for deposit in available_deposit:
            available_balance += deposit.amount
            available_balance += deposit.interest_earned
            total_interest += deposit.interest_earned

        # get all deposits
        deposits = Deposit.objects.filter(Q(user=request.user) & Q(spent=False))

        #get interest earned
        for deposit in deposits:
            available_balance +=deposit.interest_earned
            total_interest += deposit.interest_earned

        #get total balance
        #todo all unspent deposits + interest earned

        # get cumulative balance
        cumulative_balance = 0
        for deposit in deposits:
            cumulative_balance += deposit.amount

        #withdraw requests
        withdraws = None

        context = {'savings': savings, 'available_balance': available_balance, 'cumulative_balance': cumulative_balance,
                   'deposits': deposits, 'total_interest': total_interest, 'withdraws': withdraws}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        amount = float(request.POST.get('deposit_amount'))
        #check if we already have an account
        try:
            account = Account.objects.get(user=request.user, account_type='1')
        except Account.DoesNotExist:
            account = Account.objects.create(user=request.user)
        except Account.MultipleObjectsReturned:
            messages.error(request, 'Something Went Wrong: error 4**')
            return HttpResponseRedirect('investor:savings')
        try:
            if request.user.paying_account:
                Deposit.objects.create(user=request.user, amount=amount, account=account)
                messages.success(request, 'Deposit request received, Please Await Confirmation')
                #todo add and info icon on all pending deposits
            else:
                messages.error(request, 'We Could Not Process Your Deposit Request Because you have not setup your payment account.')
        except:
            #todo figure out what errors can result
            messages.error(request, 'We Could Not Process Your Deposit Request')
        return HttpResponseRedirect(reverse_lazy('investor:savings'))


@method_decorator(user_is_investor, name='get')
class SavingsWithdraw(FormView):
    def post(self, request, *args, **kwargs):
        # create a withdraw request
        amount = float(request.POST.get('withdraw_amount'))
        available_balance = float(request.POST.get('available_balance'))
        if amount <= available_balance:
            # created withdraw request
            try:
                Withdraw.objects.create(user=request.user, amount=amount)
                messages.success(request, 'Your Withdraw request has been submitted and is awaiting approval')
            except:
                messages.error(request, 'Something Went Horribly wrong ;-)')
        else:
            messages.error(request, 'You asked to withdraw more money than you have in your available balance, we can\'t do that.')
            return HttpResponseRedirect(reverse_lazy('investor:savings'))
        return HttpResponseRedirect(reverse_lazy('investor:savings'))

templates/investor/coming_soon.html
{% extends 'investor/freebie.html' %}
{% block title %}Strive!{% endblock %}
{% load static %}

{% block navbar %}
    <nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
        <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
        <div class="container">
            <div class="navbar-header">
                <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a href="http://www.creative-tim.com" class="navbar-brand">
                    Strive!
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right navbar-uppercase">
                    <li>
                        <a href="http://www.creative-tim.com/product/gaia-bootstrap-template-pro" target="_blank">Get Help</a>
                    </li>
                    <li class="dropdown">
                        <a href="#gaia" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-share-alt"></i> Share
                        </a>
                        <ul class="dropdown-menu dropdown-danger">
                            <li>
                                <a href="#"><i class="fa fa-facebook-square"></i> Facebook</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="btn btn-danger btn-fill">Login(Coming Soon)</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>
    {% endblock navbar %}

{% block hero %}
    <div class="section section-header">
        <div class="parallax filter filter-color-red">
            <div class="image"
                style="background-image: url('{% static 'investor/landing/assets/img/header-1.jpeg' %}')">
            </div>
            <div class="container">
                <div class="content">
                    <div class="title-area">
                        <p>Coming Soon...</p>
                        <h1 class="title-modern">Strive</h1>
                        <h2>Your Road To Financial Freedom Starts Here...</h2>
                        <div class="separator line-separator">♦</div>
                    </div>

                    <div class="button-get-started">
                        <a href="#" class="btn btn-white btn-fill btn-lg ">
                            Coming Soon...
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock hero %}

{% block services %}{% endblock %}
{% block who_we_are %}{% endblock %}
{% block testimonials %}{% endblock %}
{% block get_started %}{% endblock %}
{% block footer %}{% endblock %}

templates/investor/dash.html
{% extends 'presento/base.html' %}
{% block title %}Home{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block who_we_are %}
    Account RoundUp
    actual balance
    available balance
{% endblock %}

{% block portfolio_section %}
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Strive Dashboard</h3>
            <small>✻ Overview of your Strive account ✻ <br>{{ request.user.get_full_name }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}

          </div>
        </div>

         <div class="row">

          <div class="col-md-6">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">Savings <a href="{% url 'investor:savings' %}" aria-expanded="false" aria-controls="unpaid"><small>Details</small></a></h5>
                  <p class="card-category">Let Your Money Work For You By Saving and earning interest.</p>
                <p class="card-footer">
                   <strong>K {{ savings }}</strong> <br>
                </p>
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="card demo-icons">
              <div class="card-header">
                <h5 class="card-title">Loans <a href="{% url 'loans:home' %}" aria-expanded="false" aria-controls="unpaid"><small>Details</small></a></h5>
                  <p class="card-category">Get an easy loan to help financing a venture.</p>
                <p class="card-footer">
                    <strong>K {{ loans }}</strong><br>
                </p>
              </div>
            </div>
          </div>

        </div>
      </div>
          <hr>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>

    {% endblock portfolio_section %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}

templates/investor/savings.html
{% extends 'presento/base.html' %}
{% block title %}Savings{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block testimonials_section%}{% endblock %}

{% block hero %}{% endblock %}
{% block services_section %}{% endblock %}
{% block counts_section %}{% endblock %}
{% block pricing_section %}{% endblock %}
{% block team_section %}{% endblock %}

{% block portfolio_section %}
    <!-- The Modals-->
    <!--Deposit Instruction Modal-->
     <div class="modal fade" id="depositInstruction" tabindex="-1" role="dialog" aria-labelledby="depositInstruction" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="depositInstructionTitle">Deposit Instructions</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalBody">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" data-toggle="modal" class="btn btn-primary" id="confirmDeposit">Confirm</button>
                 </div>
            </div>

        </div>
     </div>

     <!--Deposit Form Modal-->
     <div class="modal fade" id="depositModel" tabindex="-1" role="dialog" aria-labelledby="depositModelTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="depositModelTitle">Savings Deposit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <form method="post" action="" id="depositForm">
                        {% csrf_token %}
                        <input type="hidden" value="{{ user.paying_account }}" name="paying_account">
                        <input class="form-control" type="number" step="any" placeholder="Enter Deposit Amount" name="deposit_amount" required>
                        <br>
                        <button type="submit" class="btn btn-primary" id="make_deposit">Make Deposit</button>
                    </form>
                </div>
            </div>

        </div>
     </div>

    <!--withdraw Modal-->
     <div class="modal fade" id="withdrawModal" tabindex="-1" role="dialog" aria-labelledby="withdrawModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="withdrawModalTitle">Savings Withdraw</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <span>Maximum You Can Withdraw Is ZMW {{ available_balance }}</span>
                    <form method="post" action="{% url 'investor:savings_withdraw' %}" id="depositForm">
                        {% csrf_token %}
                        <input type="hidden" name="available_balance" value="{{ available_balance }}">
                        <input class="form-control" type="number" step="any" placeholder="Enter Withdraw Amount" name="withdraw_amount" required max="{{ available_balance }}" min="10">
                        <br>
                        <button type="submit" class="btn btn-primary" id="withdraw">Withdraw</button>
                    </form>
                </div>
            </div>

        </div>
     </div>

    <!--withdraw list Modal-->
    <div class="modal fade" id="withdrawListModal" tabindex="-1" role="dialog" aria-labelledby="withdrawListModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="withdrawListModalTitle">Withdraw List</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                {% if withdraws %}
                    <div class="table-responsive">
				        <table class="table table-striped">
                    <thead>
						<tr>
							<th>No.</th>
							<th>Amount</th>
							<th>Date Of Request</th>
							<th>Status</th>
						</tr>
					</thead>

					<tbody id="inv_tbody">
                    {% for withdraw in withdraws %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
							<td>ZMW {{ withdraw.amount }}</td>
							<td>{{ withdraw.date }}</td>
                            <td
                                    {% if deposit.status == '1' %}
                                    class="text-info"
                                    {% else %}
                                    class="text-success"
                                    {% endif %}
                            >{{ withdraw.get_status_display }}</td>
						</tr>

                    {% endfor %}
					</tbody>
				</table>
			        </div>
                {% else %}
                    <h5 class="modal-title" id="withdrawListModalTitle">No Withdraws</h5>
                {% endif %}
                </div>
            </div>

        </div>
     </div>
    <!-- End The Modals-->

    <section class="contact"></section>
    <section id="services" class="services "></section>
     <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Savings</h3>
            <small>✻ A Breakdown Of Your Savings ✻ <br>{{ request.user.get_full_name }}</small>
          </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
              {% include 'partials/messages.html' %}
          </div>
        </div>

         <div class="row">
         {% if savings %}
             <div class="col-md-12">
            <div class="card demo icon">
              <div class="card-header">
                <h5 class="card-title">{{ savings.user.get_full_name }}</h5>
                <h6 class="card-category">
                    <strong>
                    Cumulative Balance: ZMW {{ savings.get_savings_total.0 }}<br>
                    Interest Earned: ZMW {{ total_interest }}<br>
                    Total Balance: ZMW {{ savings.get_savings_total.1 }}<br>
                    Available Balance: ZMW {{ available_balance }}
                    </strong>

                </h6>
              </div>
              <div class="card-body">
                  <div class="table-responsive">
				<table class="table table-striped">
                    <thead>
						<tr>
							<th>No.</th>
							<th>Amount</th>
							<th>Date Of Deposit</th>
                            <th>Interest Earned</th>
							<th>Status</th>
						</tr>
					</thead>

					<tbody id="inv_tbody">
                    {% for deposit in deposits %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
							<td>{{ deposit.amount }}</td>
							<td>{{ deposit.date }}</td>
							<td>ZMW {{ deposit.interest_earned}}</td>
                            <td
                                    {% if deposit.status == '1' %}
                                    class="text-info"
                                    {% elif deposit.status == '2' %}
                                    class="text-primary"
                                    {% else %}
                                    class="text-success"
                                    {% endif %}
                            >{{ deposit.get_status_display }}</td>
						</tr>

                    {% endfor %}
					</tbody>
				</table>
			</div>

              </div>

              <div class="card-footer">
                  <button type="button" class="btn btn-success" data-toggle="modal" data-target="#depositModel">Deposit Funds</button>
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#withdrawModal">Withdraw Funds</button>
                  <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#withdrawListModal">List Withdraw Requests</button>
              </div>
            </div>
          </div>
         {% else %}
             <div class="col-md-auto col-lg-12 col-sm-12 text-center">
                <div>
                    <h5 class="text-info">Your Have No Savings Yet.<br> Use The Deposit Button Below to Start Saving</h5>
                </div>
             </div>
<br>
             <div class="col-md-12 col-lg-12 col-sm-12 text-center">
             <button type="button" data-toggle="modal" class="btn btn-success" data-target="#depositModel">Deposit</button><br>
             <small>Deposit Money to start saving with us.</small>
             </div>

            {% endif %}


        </div>
      </div>

    </section><!-- End Portfolio Section -->
    <section class="services"></section>
    {% endblock portfolio_section %}

{% block javascript %}
    <script src="{% static 'investor/js/strive.js' %}" type="module"></script>
{% endblock %}

{% block about_section %}{% endblock %}
{% block tabs_section %}{% endblock %}
{% block clients_section %}{% endblock %}
{% block faq %}{% endblock %}
{% block contact_section %}{% endblock %}
{% block footer %}{% endblock %}